# handlers/main.yml
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart gx-it-proxy
  ansible.builtin.systemd:
    name: galaxy-gx-it-proxy.service
    state: restarted
  when: "'galaxy-gx-it-proxy.service' in ansible_facts.services"
  
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: "'nginx.service' in ansible_facts.services"