---
- hosts: galaxyservers
  become: true
  become_user: root

  vars:
    # galaxy_root: "{{ ansible_env.HOME }}/projects/galaxy" # To avoid accesses problems locally - use the home directory of the user running Ansible
    galaxy_root: /srv/galaxy/server
    moonshot_dir: "{{ galaxy_root }}/tools/moonshot"
    tool_conf: "{{ galaxy_root }}/config/tool_conf.xml.sample"
    ansible_user_id: "{{ ansible_env.USER }}"
    datatypes_conf_dir: "{{ galaxy_root }}/config/datatypes_conf.xml.sample"
    datatypes_dir: "{{ galaxy_root }}/lib/galaxy/datatypes"
    designite_tool_root: "{{ ansible_env.HOME }}/projects/designite_java_Tool"
    designite_repo_url: "https://github.com/tushartushar/DesigniteJava.git"
    gx_it_proxy_bin: "/usr/local/bin/gx-it-proxy"  
    gx_it_proxy_ip: "127.0.0.1"
    gx_it_proxy_port: 4002
    gx_it_proxy_extra_opts: "--proxyPathPrefix /interactivetool/ep --verbose"
    nginx_galaxy_path: "/etc/nginx/sites-available/galaxy"
    interactivetools_map: /srv/galaxy/var/interactivetools_map.sqlite # Make sure this path is correct and writable by the Galaxy user

  roles:
    - moonshot.general
    - moonshot.extraction-tool
    - moonshot.code-to-spif-tool
    - moonshot.spif-to-svif-tool
    - moonshot.classviz-tool
    - { role: designite.install, tags: ["designite"] }