---
- name: Ensure Docker engine is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes
  become: yes

- name: Install Python Docker SDK
  apt:
    name: python3-docker
    state: present
    update_cache: yes
  become: yes

- import_tasks: datatypes_management.yml
- import_tasks: gx-it-proxy.yml
- import_tasks: update.yml
