---
- name: Clone Code-to-SPIF-Tool into Galaxy
  git:
    repo: "https://github.com/Software-Analytics-Visualisation-Team/Andromeda-Code-Parsing-Tool.git"
    dest: "{{ moonshot_dir }}/Code-to-SPIF-Tool"
    version: main
    update: yes
    force: yes

- name: Add ANTLR runtime requirement
  lineinfile:
    path: "{{ moonshot_dir }}/Code-to-SPIF-Tool/zip_to_spif.xml"
    insertafter: "^  <requirements>$"
    line: '    <requirement type="package">antlr4-python3-runtime==4.12.0</requirement>'

- name: Add RDFLib requirement
  lineinfile:
    path: "{{ moonshot_dir }}/Code-to-SPIF-Tool/zip_to_spif.xml"
    insertafter: "^  <requirements>$"
    line: '    <requirement type="package">rdflib</requirement>'
