# 1) Clone the Designite-Java-Tool repository
- name: Ensure moonshot tools directory exists
  file:
    path: "{{ moonshot_dir }}"
    state: directory
    mode: "0755"

- name: Clone Designite-Java-Tool (Galaxy wrapper) into tools/moonshot
  git:
    repo: "https://github.com/Software-Analytics-Visualisation-Team/Designite-Java-Tool.git"
    dest: "{{ moonshot_dir }}/Designite-Java-Tool"
    version: "main"
    update: yes

# 2) Choose URL (Pro if key provided, else Community)
- name: Set Designite JAR URL (Pro if key provided, else Community)
  set_fact:
    designite_effective_url: >-
      {{ (designite_license_key | default('') | length > 0)
         | ternary( designite_pro_url | default('https://www.designite-tools.com/assets/DesigniteJava.jar'),
                    designite_community_url | default('https://www.designite-tools.com/assets/DesigniteJavaCommunity.jar')) }}

- name: Download DesigniteJava JAR (Pro or Community)
  get_url:
    url: "{{ designite_effective_url }}"
    dest: "{{ moonshot_dir }}/Designite-Java-Tool/DesigniteJava.jar"
    mode: "0644"
    force: yes        
    validate_certs: yes

# 3) Register Designite license only if key provided
- name: Register Designite license (node-locked, Pro)
  command: "java -jar DesigniteJava.jar -r {{ designite_license_key }}"
  args:
    chdir: "{{ moonshot_dir }}/Designite-Java-Tool"
  become: true #comment locally
  become_user: "{{ galaxy_user_name | default('galaxy') }}"  #comment locally
  when: (designite_license_key | default('')) | length > 0
  changed_when: false
  failed_when: false
  no_log: true  #comment locally

# 4) Declare tool in Galaxy panel
- name: Register Designite tool in Galaxy tool panel
  blockinfile:
    path: "{{ tool_conf }}"
    marker: "<!-- {mark} DESIGNITE TOOL -->"
    insertafter: "<!-- Moonshot tools will be added here -->"
    block: |
      <tool file="moonshot/Designite-Java-Tool/designite_java.xml" />
